services:
  - type: web
    name: chat-with-pdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run chat.py --server.port 10001 --server.enableCORS=false
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        sync: false
      - key: LANGUAGE_MODEL
        sync: false
    plan: free
    branch: main
    autoDeploy: true
